export const ACTION_POINT_ADD = 'ACTION_POINT_ADD';
export const ACTION_POINT_REMOVE = 'ACTION_POINT_REMOVE';
export const ACTION_POINT_CHANGE_LOCATION = 'ACTION_POINT_CHANGE_LOCATION';
export const ACTION_POINT_LIST_CHANGE_POSITION = 'ACTION_POINT_LIST_CHANGE_POSITION';
